#ifndef QTSINGLEAPPLICATION_GLOBAL_H
#define QTSINGLEAPPLICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QTSINGLEAPPLICATION_LIB
# define QTSINGLEAPPLICATION_EXPORT Q_DECL_EXPORT
#else
# define QTSINGLEAPPLICATION_EXPORT Q_DECL_IMPORT
#endif

#endif // QTSINGLEAPPLICATION_GLOBAL_H
